"""Criar

Revision ID: bf87b808d0b5
Revises: 
Create Date: 2025-05-22 11:20:00.821496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf87b808d0b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('plano', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_confirmado', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=16), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina', sa.String(length=100), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.Column('data_prova', sa.Date(), nullable=False),
    sa.Column('arquivo_enunciado', sa.String(length=100), nullable=False),
    sa.Column('arquivo_resolucao', sa.String(length=100), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('data_submissao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacoes_upgrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('aprovada', sa.Boolean(), nullable=False),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autores', sa.String(length=200), nullable=False),
    sa.Column('disciplina', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('palavras_chave', sa.String(length=200), nullable=True),
    sa.Column('nivel_acesso', sa.String(length=20), nullable=False),
    sa.Column('arquivo', sa.String(length=100), nullable=False),
    sa.Column('aprovado', sa.Boolean(), nullable=False),
    sa.Column('data_submissao', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabalhos')
    op.drop_table('solicitacoes_upgrade')
    op.drop_table('provas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
